JupiterOne/graph-vsphere

CHANGELOG.md, Dockerfile, docker.env.example, docker.package.json, docs/development.md, docs/jupiterone.md
=> fix docker image, update docs around docker image

.env.example, .github/workflows/codeql-analysis.yml, CHANGELOG.md, docs/development.md, package.json, src/client.ts, src/config.ts
Removed hardcoded text `vmwarevmc.com` that was causing issues with auth.
https://jupiterone.atlassian.net/browse/INT-6361
API
relationships, and their property names, to ensure those questions still
function with my changes.
=> INT-6361 - Remove hardcored URI

.github/workflows/codeql-analysis.yml, package.json, src/config.ts, src/steps/host/converter.ts, src/steps/network/index.ts, yarn.lock
Fixes for issues found during local execution.
API …
=> INT-6503 - Local execution fixes

CHANGELOG.md, docker.package.json, package.json
Release version 1.2.0
API
relationships, and their property …
=> Release 1.2.0

docs/jupiterone.md
Small update to specify recommended permissions for credentials.
API
reviewed all existing managed questions referencing the …
=> Specifying recommended permissions for credentials in documentation

src/__recordings__/check-version_3345618818/recording.har, src/client.test.ts, src/client.ts, src/config.ts, src/steps/cluster/index.ts, src/steps/data-center/index.ts, src/steps/datastore/index.ts, src/steps/distributed-switch/index.ts, src/steps/host/index.ts, src/steps/namespace/index.ts, src/steps/network/index.ts, src/steps/virtual-machine/index.ts, src/types.ts
Adding a query to a vSphere endpoint to get the current API version.  I went ahead and updated the VM guest identity query to check that we're on a supported version before running it.  A future PR will add similar checks to the namespace endpoints for proper handling of version 6.5.
API
[JupiterOne data …
=> INT-6768 - Adding version check for future backwards compatibility work

CHANGELOG.md, docker.package.json, package.json
=> Release 1.4.0

package.json, src/__recordings__/check-version_3345618818/recording.har, src/client.ts, src/config.ts, src/steps/cluster/__recordings__/fetch-cluster_3473008108/recording.har, src/steps/data-center/__recordings__/fetch-data-center_4184374324/recording.har, src/steps/datastore/__recordings__/fetch-datastore_1376388411/recording.har, src/steps/distributed-switch/__recordings__/fetch-distributed-switch_429830286/recording.har, src/steps/host/__recordings__/fetch-host_4030657364/recording.har, src/steps/namespace/__recordings__/fetch-namespace_658612017/recording.har, src/steps/network/__recordings__/fetch-network_923406696/recording.har, src/steps/virtual-machine/__recordings__/fetch-vm_981946273/recording.har, src/steps/virtual-machine/index.ts, yarn.lock
Additional updates based on user testing feedback.  Primarily, the session creation needed backward compatibility included since we won't yet know the API version we're querying.
API
to ensure that any new entities/relationships, and relevant …
=> INT-6770 - Additional vSphere feedback

src/__recordings__/auth-failure_2060467788/recording.har, src/__recordings__/iterate-vms_3409002706/recording.har, src/client.test.ts, src/client.ts, src/steps/network/index.ts, src/steps/virtual-machine/__recordings__/fetch-vm_981946273/recording.har, src/steps/virtual-machine/index.ts
Updating the query that lists VMs to query by host.  This reduces the likelihood that we will hit the API limit of 4000 VMs returned by that endpoint.
API
match the recommended …
=> INT-6770 - Query VMs by host

CHANGELOG.md, docker.package.json, package.json
=> Release 1.5.0

CHANGELOG.md, docker.package.json, package.json, src/client.ts
Catching instances where we are unable to successfully query for a list of VMs for a particular host.
API
reviewed all existing …
=> Catching VM list errors

CHANGELOG.md, package.json, src/steps/virtual-machine/index.ts
=> Release 1.5.2

CHANGELOG.md, package.json, src/client.test.ts, src/client.ts
Added a new event.
API
relationships, and their property …
=> Added version event

CHANGELOG.md, src/client.test.ts, src/client.ts, src/steps/virtual-machine/converter.ts, src/steps/virtual-machine/index.ts, src/types.ts
Modified the Virtual-Machine step to collect MAC addresses for each VM
API
reviewed all existing managed questions referencing …
=> MAC Address

.github/workflows/build.yml, .gitignore, CHANGELOG.md, README.md, package.json, yarn.lock
=> Converting release process to use auto.

CHANGELOG.md
Updating CHANGELOG to reflect correct version for auto changes after required re-run to fix permissions issues.
API
reviewed all …
=> Updating CHANGELOG to reflect correct version

docs/jupiterone.md, src/client.ts
=> INT-7368 - Documentation update for distributed switch failures

.github/workflows/package-publish.yml, Dockerfile-Alternate
Add the build and packaging steps to create a local GH package and signature
=> Adding build and package workflow

docs/development.md, docs/jupiterone.md
Updates docs to include a description of how to configure the firewall.
=> Updating docs

.github/workflows/package-publish.yml
=> Fix collector workflow

src/client.ts, src/config.ts
=> INT-10833: add uses NSX dynamic config
